import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import AuthProvider from '@/providers/AuthProvider'

const inter = Inter({ subsets: ['latin'] })
 
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <div className='max-w-[1920px] h-[1080px] mx-auto'>
            <Navbar></Navbar>
            <main>{children}</main>
          </div>
        </AuthProvider>
      </body>
    </html>
  )
}

export default RootLayout;
